//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int AboutId { get; set; }
        public string AboutTitle { get; set; }
        public string AboutDetails { get; set; }
        public string AboutImageLink { get; set; }
        public string CvLink { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
