//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutPersonalInfo
    {
        public int AboutPersonalInfoId { get; set; }
        public Nullable<int> AboutId { get; set; }
        public string PersonalName { get; set; }
        public string PersonalDetails { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateOn { get; set; }
    }
}
