//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditId { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string HostName { get; set; }
        public string IpAddress { get; set; }
        public string PcName { get; set; }
        public string Browser { get; set; }
        public string OsInfo { get; set; }
        public string RequestedUrl { get; set; }
        public string Url { get; set; }
        public string Message { get; set; }
    }
}
