//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesCms : DbContext
    {
        public EntitiesCms()
            : base("name=EntitiesCms")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AboutSkill> AboutSkills { get; set; }
        public virtual DbSet<AboutPersonalInfo> AboutPersonalInfoes { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<PortfolioType> PortfolioTypes { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UplodImage> UplodImages { get; set; }
    }
}
