//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int SystemSettings { get; set; }
        public Nullable<int> PerDayMaxMessageSent { get; set; }
        public string EmailContent { get; set; }
    }
}
